# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
torch_dtype: null

# Data training arguments
# For definitions, see: src/h4/training/config.py
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 10000
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: llama-8b-instruct-wpo
learning_rate: 1.0e-6
log_level: info
logging_steps: 10
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 2
optim: adamw_torch
output_dir: outputs/llama-8b-instruct-wpo
per_device_train_batch_size: 2
per_device_eval_batch_size: 8
push_to_hub: false
save_strategy: "steps"
save_steps: 10000
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
report_to: "none"